name: executing when pushed on main
on:
  push:
    branches: [ main ]
jobs:
  deployment-test:
    name: "Main Branch test"
    runs-on: ubuntu-latest
    steps:
    - name: Executing remote ssh command on VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: sudo sh ~/ttt.sh main